Feat/expenses services
Grupo-Betuel/travelm. pull request #46
Opened 2024-08-25 21:49 UTC by AnTonyFrontDev

![image](https://github.com/user-attachments/assets/137b4809-c5ed-4ad7-b999-babaaacb3188)
![image](https://github.com/user-attachments/assets/aca7dd88-1b0a-4e12-9a60-11541896fd19)
#5

2024-09-09 17:16 UTC, wpadilla requested changes
Mete mano con estos cambios antes de continuar con las demas tareas @AnTonyFrontDev 🔥

2024-09-09 17:16 UTC, wpadilla commented on src/models/interfaces/ExpensesModel.ts
Este archivo debe ser creado en la carpeta de models en lugar de `interfaces` ya existe un `expenseModel.ts`  en la carpeta de models, pero no se usa, puedes reemplazar el codigo de ese archivo por este.

2024-09-09 17:16 UTC, wpadilla commented on src/pages/dashboard/excursion/components/ExpensesDialog.tsx
evita crear componentes Dialogos, en lugar de eso crea un componente ExpensesHandler y usalo dentro de un dialogo, asi el componente podra ser reutilizable en otros modulos de otras formas y no unicamente como un dialog

2024-09-09 17:16 UTC, wpadilla commented on src/pages/dashboard/excursion/components/FinanceDetail.tsx
> +    const totalAmount = expenses?.reduce((acc, expense) => acc + (expense.finance?.price ?? 0), 0);
utilizar useMemo aqui para evitar que se ejecute reduce cada vez que el componente se actualice

2024-09-09 17:16 UTC, wpadilla commented on src/pages/dashboard/excursion/components/FinanceHandler.tsx
> +    options?: boolean;
en lugar de hacerla boolean deberia ser 

NOTA: este enum debe estar en el achivo `financeModel.ts`
```export enum FinanceOptionEnum {
    COST= "cost",
    COUPLE= "couple",
    CHILDREN= "children",
}

options: FinanceOptionEnum[]
```

si option tiene algun valor entonces habilitar el boton y solo mostrar las opciones que se hayan pasado en el arreglo de options

ej:
`options={ [FinanceOptionEnum.COST, FinanceOptionEnum.COUPLE] }`

2024-09-10 02:39 UTC, AnTonyFrontDev reviewed
Revisado

2024-09-10 21:31 UTC, merged