Cambios Servicios y Comentarios
Grupo-Betuel/travelm. pull request #47
Opened 2024-09-09 15:20 UTC by AnTonyFrontDev

@wpadilla 

cambios entorno agregar hacientos, crud de gastos, crud de comentarios dentro de servicios

2024-09-09 17:39 UTC, wpadilla requested changes

2024-09-09 17:39 UTC, wpadilla commented on src/models/commentModel.ts
> +export interface IComments {
Debe ser singular `IComment` ya que hace referencia a una entidad, no a un listado o arreglo. solo debe ir en plurar la propiedad comments de excursion ya que ahi si se hace referencia a varios comentarios.

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/ClientForm.tsx
> +            console.log('relatedService', relatedService);
eliminar console.log

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/ClientForm.tsx
> +            setService(initialClient.services?.[0]);
utilizar currentService aqui (los clientes vienen con esa propiedad del backend) Si siempre tomas el primer servicio habra problemas cuando el cliente sea parte de otra excursion y se mezclaran los datos, el cliente siempre sera uno, pero podra participar de muchas excursiones y para eso es el arreglo de servicios, con cada excursion en la que participa se le crea un nuevo servicio.

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/ClientForm.tsx
>              const relatedService = foundClient.services.find(s => s.excursionId === service?.excursionId);
Esto puede ser reemplazado por la propiedad currentService, ya el backend se encarga de hacer esta busqueda.

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/CommentDialog.tsx
Al igual que con el ExpensesDialog crea un commentHandler en lugar de un dialogo y agrega la propiedad dialog como esta en el organizationForm

`dialog?: ICustomComponentDialog;`

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/FinanceDetail.tsx
>      console.log('expenses',expenses)
remove console.log

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/FinanceDetail.tsx
> +                    console.log("Service found:", seats); // Debugging line
remove console

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/FinanceDetail.tsx
> +        () => profit * totalSeats - investedInFreeClients,
para evitar fallos en la logica encapsula en parentesis la multiplicacion inicial y luego restalo

`(profit * totalSeats) - investedInFreeClients`

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/ServiceHandler.tsx
> +    console.log('service prueba', services)
remove

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/ServiceHandler.tsx
> +                            <Option key={type} value={type}>{serviceStatusLabels?[type] : ''}</Option>
necesita un punto 👀

`serviceStatusLabels?.[type]`

2024-09-09 17:39 UTC, wpadilla commented on src/pages/dashboard/excursion/components/ServiceHandler.tsx
> +                            <Option key={type} value={type}>{serviceStatusLabels?[type] : ''}</Option>
esto seria lo correcto
{serviceStatusLabels?.[type] || ''}

imagino que te esaba apareciendo el texto entre corchetes

2024-09-10 03:42 UTC, AnTonyFrontDev reviewed
revisado

2024-09-10 03:42 UTC, AnTonyFrontDev commented on src/pages/dashboard/excursion/components/ServiceHandler.tsx
> +                            <Option key={type} value={type}>{serviceStatusLabels?[type] : ''}</Option>
no esta mapeando directamente los type no entrando directamente a type por eso no tiene el punto. funciona sin el ? pero da error de que podria ser undefined

2024-09-10 21:24 UTC, wpadilla approved these changes
Excelente!

2024-09-10 21:31 UTC, merged